apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yosegaki-db
  namespace: yosegaki
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 1Gi
